In [1]:
#cargamos el dataset
#utilizamos random forest
import pandas as pd  
import numpy as np 

prueba2 = pd.read_csv("dataset-prueba2.csv",index_col=0)
#subdividimos el data set
y=prueba2.iloc[:,63:64]
X=prueba2.iloc[:,0:63]

In [2]:
#divisimos en conjunto de pruebas y entrenamiento
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [3]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(n_estimators=20, random_state=0)  
classifier.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=20, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [4]:
y_pred = classifier.predict(X_test)

In [5]:
#utilizamos una metrica para evaluar este modelo
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  
print(accuracy_score(y_test, y_pred))

[[580   1   7]
 [  0 560  33]
 [ 20  20 530]]
              precision    recall  f1-score   support

           0       0.97      0.99      0.98       588
           1       0.96      0.94      0.95       593
           2       0.93      0.93      0.93       570

   micro avg       0.95      0.95      0.95      1751
   macro avg       0.95      0.95      0.95      1751
weighted avg       0.95      0.95      0.95      1751

0.9537407195888064


In [ ]:
#utilizando random forest obtenemos un modelo mucho mejor que los dos anteriores.